import fs from "node:fs";
import path from "node:path";

const filePath = path.resolve("lib/i18n/ui.ts");
let content = fs.readFileSync(filePath, "utf8");

// Remove any prior injected block right before const dictionaries
content = content.replace(/\/\/ --- BEGIN ROZNAMCHA 5-LANG INJECTION ---[\s\S]*?\/\/ --- END ROZNAMCHA 5-LANG INJECTION ---\r?\n/g, "");

const injection = `// --- BEGIN ROZNAMCHA 5-LANG INJECTION ---
const rozrep_en = {
  "rozrep.sno": "S.No",
  "rozrep.date": "Date",
  "rozrep.entry_serial": "Entry Serial",
  "rozrep.country": "Country",
  "rozrep.branch": "Branch",
  "rozrep.user": "User",
  "rozrep.entry_type": "Entry Type",
  "rozrep.roznamcha_type": "Roznamcha Type",
  "rozrep.account_no": "Account No",
  "rozrep.account_name": "Account Name",
  "rozrep.narration": "Narration / Remarks",
  "rozrep.currency": "Currency",
  "rozrep.debit": "Debit",
  "rozrep.credit": "Credit",
  "rozrep.balance": "Balance",
  "rozrep.bill_ref": "Bill/Ref No",
  "rozrep.status": "Status",
  "rozrep.totals": "Totals",
  "rozrep.country_label": "COUNTRY:",
  "rozrep.branch_name_label": "BRANCH NAME:",
  "rozrep.user_id_label": "USER ID:",
  "rozrep.user_name_label": "USER NAME:",
  "rozrep.role_label": "ROLE:",
  "rozrep.datetime_label": "DATE & TIME:",
  "rozrep.status_label": "STATUS:",
  "rozrep.active": "ACTIVE",
  "rozrep.branch_user_details": "BRANCH & USER DETAILS",
  "rozrep.global_financial_summary": "GLOBAL FINANCIAL SUMMARY",
  "rozrep.total_global_entries": "TOTAL GLOBAL ENTRIES:",
  "rozrep.total_bill_entries": "TOTAL BILL ENTRIES:",
  "rozrep.cleared_entries": "CLEARED ENTRIES:",
  "rozrep.remaining_entries": "REMAINING ENTRIES:",
  "rozrep.system_status": "SYSTEM STATUS:",
  "rozrep.online_synced": "ONLINE & SYNCED",
  "rozrep.from_date": "From Date",
  "rozrep.to_date": "To Date",
  "rozrep.all_types": "All Types",
  "rozrep.debit_credit": "Debit / Credit",
  "rozrep.all": "All",
  "rozrep.draft": "Draft",
  "rozrep.posted": "Posted",
  "rozrep.transferred": "Transferred",
  "rozrep.cancelled": "Cancelled",
  "rozrep.reference_no": "Reference No",
  "rozrep.filter_entries_ph": "Filter entries...",
  "rozrep.reference_ph": "Reference number",
  "rozrep.bill_no": "Bill No",
  "rozrep.bill_no_ph": "Bill number",
  "rozrep.apply_filter": "Apply",
  "rozrep.reset_filter": "Reset",
  "rozrep.reload": "Reload",
  "rozrep.actions": "Actions",
  "rozrep.back": "Back",
  "rozrep.hide_filters": "Hide Filters",
  "rozrep.search_filters": "Search / Filters",
  "rozrep.total_entries": "Total Entries",
  "rozrep.showing_page": "Showing Page",
  "rozrep.of": "of",
  "rozrep.loading_entries": "Loading Entries...",
  "rozrep.no_entries_found": "No entries found for the selected filters.",
  "rozrep.category_directory": "Roznamcha Entry Category Directory",
  "rozrep.category_directory_hint": "Click a category to filter instantly",
  "rozrep.active_view": "Active View",
  "rozrep.click_to_view": "Click to view",
  "rozrep.currency_label": "Currency",
  "roz.entry_type_po_transfer": "Purchase Booking Transfer",
  "roz.entry_type_po_adv": "Purchase Advance Payment",
  "roz.entry_type_po_rem": "Purchase Remaining Payment",
  "roz.entry_type_journal": "Journal Entry",
  "roz.entry_type_bank_dep": "Bank Deposit",
  "roz.entry_type_cash_pay": "Cash Payment",
  "roz.entry_type_cash_rec": "Cash Receipt",
  "roz.entry_type_expense": "Expense Entry",
  "roz.entry_type_fx": "Exchange Rate Gain / Loss",
  "status.posted": "Posted",
  "status.draft": "Draft",
  "status.transferred": "Transferred",
  "status.cancelled": "Cancelled"
};

const rozrep_ur = {
  "rozrep.sno": "شمار",
  "rozrep.date": "تاریخ",
  "rozrep.entry_serial": "انٹری سیریل",
  "rozrep.country": "ملک",
  "rozrep.branch": "برانچ",
  "rozrep.user": "صارف",
  "rozrep.entry_type": "انٹری کی قسم",
  "rozrep.roznamcha_type": "روزنامچہ کی قسم",
  "rozrep.account_no": "اکاؤنٹ نمبر",
  "rozrep.account_name": "اکاؤنٹ کا نام",
  "rozrep.narration": "تفصیل / ریمارکس",
  "rozrep.currency": "کرنسی",
  "rozrep.debit": "ڈیبٹ",
  "rozrep.credit": "کریڈٹ",
  "rozrep.balance": "بیلنس",
  "rozrep.bill_ref": "بل / حوالہ نمبر",
  "rozrep.status": "حیثیت",
  "rozrep.totals": "کل میزان",
  "rozrep.country_label": "ملک:",
  "rozrep.branch_name_label": "برانچ کا نام:",
  "rozrep.user_id_label": "صارف آئی ڈی:",
  "rozrep.user_name_label": "صارف کا نام:",
  "rozrep.role_label": "کردار:",
  "rozrep.datetime_label": "تاریخ و وقت:",
  "rozrep.status_label": "حیثیت:",
  "rozrep.active": "فعال",
  "rozrep.branch_user_details": "برانچ اور صارف کی تفصیلات",
  "rozrep.global_financial_summary": "عالمی مالیاتی خلاصہ",
  "rozrep.total_global_entries": "کل عالمی اندراجات:",
  "rozrep.total_bill_entries": "کل بل اندراجات:",
  "rozrep.cleared_entries": "کلیئر شدہ اندراجات:",
  "rozrep.remaining_entries": "بقیہ اندراجات:",
  "rozrep.system_status": "سسٹم کی حیثیت:",
  "rozrep.online_synced": "آن لائن اور ہم آہنگ",
  "rozrep.from_date": "شروع تاریخ",
  "rozrep.to_date": "آخری تاریخ",
  "rozrep.all_types": "تمام اقسام",
  "rozrep.debit_credit": "ڈیبٹ / کریڈٹ",
  "rozrep.all": "تمام",
  "rozrep.draft": "ڈرافٹ",
  "rozrep.posted": "پوسٹ شدہ",
  "rozrep.transferred": "منتقل شدہ",
  "rozrep.cancelled": "منسوخ",
  "rozrep.reference_no": "حوالہ نمبر",
  "rozrep.filter_entries_ph": "اندراجات تلاش کریں...",
  "rozrep.reference_ph": "حوالہ نمبر درج کریں",
  "rozrep.bill_no": "بل نمبر",
  "rozrep.bill_no_ph": "بل نمبر درج کریں",
  "rozrep.apply_filter": "لاگو کریں",
  "rozrep.reset_filter": "دوبارہ ترتیب دیں",
  "rozrep.reload": "دوبارہ لوڈ کریں",
  "rozrep.actions": "کارروائیاں",
  "rozrep.back": "واپس",
  "rozrep.hide_filters": "فلٹرز چھپائیں",
  "rozrep.search_filters": "تلاش / فلٹرز",
  "rozrep.total_entries": "کل اندراجات",
  "rozrep.showing_page": "صفحہ دکھا رہا ہے",
  "rozrep.of": "از",
  "rozrep.loading_entries": "اندراجات لوڈ ہو رہے ہیں...",
  "rozrep.no_entries_found": "منتخب کردہ فلٹرز کے لیے کوئی اندراج نہیں ملا۔",
  "rozrep.category_directory": "روزنامچہ انٹری کیٹیگری ڈائرکٹری",
  "rozrep.category_directory_hint": "فوری فلٹر کرنے کے لیے کیٹیگری پر کلک کریں",
  "rozrep.active_view": "فعال منظر",
  "rozrep.click_to_view": "دیکھنے کے لیے کلک کریں",
  "rozrep.currency_label": "کرنسی",
  "roz.entry_type_po_transfer": "خریداری بکنگ ٹرانسفر",
  "roz.entry_type_po_adv": "خریداری ایڈوانس ادائیگی",
  "roz.entry_type_po_rem": "خریداری بقیہ ادائیگی",
  "roz.entry_type_journal": "جرنل انٹری",
  "roz.entry_type_bank_dep": "بینک ڈپازٹ / جمع",
  "roz.entry_type_cash_pay": "کیش ادائیگی",
  "roz.entry_type_cash_rec": "کیش وصولی",
  "roz.entry_type_expense": "اخراجات انٹری",
  "roz.entry_type_fx": "شرح تبادلہ نفع / نقصان",
  "status.posted": "پوسٹ شدہ",
  "status.draft": "ڈرافٹ",
  "status.transferred": "منتقل شدہ",
  "status.cancelled": "منسوخ"
};

const rozrep_ar = {
  "rozrep.sno": "الرقم",
  "rozrep.date": "التاريخ",
  "rozrep.entry_serial": "الرقم التسلسلي للقيود",
  "rozrep.country": "الدولة",
  "rozrep.branch": "الفرع",
  "rozrep.user": "المستخدم",
  "rozrep.entry_type": "نوع القيد",
  "rozrep.roznamcha_type": "نوع اليومية",
  "rozrep.account_no": "رقم الحساب",
  "rozrep.account_name": "اسم الحساب",
  "rozrep.narration": "البيان / الملاحظات",
  "rozrep.currency": "العملة",
  "rozrep.debit": "مدين",
  "rozrep.credit": "دائن",
  "rozrep.balance": "الرصيد",
  "rozrep.bill_ref": "رقم الفاتورة / المرجع",
  "rozrep.status": "الحالة",
  "rozrep.totals": "الإجمالي",
  "rozrep.country_label": "الدولة:",
  "rozrep.branch_name_label": "اسم الفرع:",
  "rozrep.user_id_label": "معرف المستخدم:",
  "rozrep.user_name_label": "اسم المستخدم:",
  "rozrep.role_label": "الدور:",
  "rozrep.datetime_label": "التاريخ والوقت:",
  "rozrep.status_label": "الحالة:",
  "rozrep.active": "نشط",
  "rozrep.branch_user_details": "تفاصيل الفرع والمستخدم",
  "rozrep.global_financial_summary": "الملخص المالي العام",
  "rozrep.total_global_entries": "إجمالي القيود العامة:",
  "rozrep.total_bill_entries": "إجمالي قيود الفواتير:",
  "rozrep.cleared_entries": "القيود المسواة:",
  "rozrep.remaining_entries": "القيود المتبقية:",
  "rozrep.system_status": "حالة النظام:",
  "rozrep.online_synced": "متصل ومحدث",
  "rozrep.from_date": "من تاريخ",
  "rozrep.to_date": "إلى تاريخ",
  "rozrep.all_types": "جميع الأنواع",
  "rozrep.debit_credit": "مدين / دائن",
  "rozrep.all": "الكل",
  "rozrep.draft": "مسودة",
  "rozrep.posted": "مرحل",
  "rozrep.transferred": "محول",
  "rozrep.cancelled": "ملغى",
  "rozrep.reference_no": "رقم المرجع",
  "rozrep.filter_entries_ph": "البحث في القيود...",
  "rozrep.reference_ph": "أدخل رقم المرجع",
  "rozrep.bill_no": "رقم الفاتورة",
  "rozrep.bill_no_ph": "أدخل رقم الفاتورة",
  "rozrep.apply_filter": "تطبيق",
  "rozrep.reset_filter": "إعادة تعيين",
  "rozrep.reload": "تحديث",
  "rozrep.actions": "الإجراءات",
  "rozrep.back": "رجوع",
  "rozrep.hide_filters": "إخفاء الفلاتر",
  "rozrep.search_filters": "بحث / فلاتر",
  "rozrep.total_entries": "إجمالي القيود",
  "rozrep.showing_page": "عرض الصفحة",
  "rozrep.of": "من",
  "rozrep.loading_entries": "جاري تحميل القيود...",
  "rozrep.no_entries_found": "لم يتم العثور على قيود مطابقة للفلاتر المحددة.",
  "rozrep.category_directory": "دليل تصنيفات قيود اليومية",
  "rozrep.category_directory_hint": "انقر فوق تصنيف للتصفية الفورية",
  "rozrep.active_view": "العرض الحالي",
  "rozrep.click_to_view": "انقر للعرض",
  "rozrep.currency_label": "العملة",
  "roz.entry_type_po_transfer": "تحويل حجز الشراء",
  "roz.entry_type_po_adv": "دفعة مقدمة للشراء",
  "roz.entry_type_po_rem": "دفعة متبقية للشراء",
  "roz.entry_type_journal": "قيد يومية",
  "roz.entry_type_bank_dep": "إيداع بنكي",
  "roz.entry_type_cash_pay": "دفع نقدي",
  "roz.entry_type_cash_rec": "قبض نقدي",
  "roz.entry_type_expense": "قيد مصروفات",
  "roz.entry_type_fx": "أرباح / خسائر فروق العملة",
  "status.posted": "مرحل",
  "status.draft": "مسودة",
  "status.transferred": "محول",
  "status.cancelled": "ملغى"
};

const rozrep_fa = {
  "rozrep.sno": "ردیف",
  "rozrep.date": "تاریخ",
  "rozrep.entry_serial": "شماره سریال سند",
  "rozrep.country": "کشور",
  "rozrep.branch": "شعبه",
  "rozrep.user": "کاربر",
  "rozrep.entry_type": "نوع سند",
  "rozrep.roznamcha_type": "نوع روزنامچه",
  "rozrep.account_no": "شماره حساب",
  "rozrep.account_name": "نام حساب",
  "rozrep.narration": "شرح سند / ملاحظات",
  "rozrep.currency": "ارز",
  "rozrep.debit": "بدهکار",
  "rozrep.credit": "بستانکار",
  "rozrep.balance": "مانده",
  "rozrep.bill_ref": "شماره فاکتور / عطف",
  "rozrep.status": "وضعیت",
  "rozrep.totals": "مجموع کل",
  "rozrep.country_label": "کشور:",
  "rozrep.branch_name_label": "نام شعبه:",
  "rozrep.user_id_label": "شناسه کاربر:",
  "rozrep.user_name_label": "نام کاربر:",
  "rozrep.role_label": "نقش:",
  "rozrep.datetime_label": "تاریخ و ساعت:",
  "rozrep.status_label": "وضعیت:",
  "rozrep.active": "فعال",
  "rozrep.branch_user_details": "جزئیات شعبه و کاربر",
  "rozrep.global_financial_summary": "خلاصه مالی کل",
  "rozrep.total_global_entries": "کل اسناد ثبت شده:",
  "rozrep.total_bill_entries": "کل اسناد فاکتور:",
  "rozrep.cleared_entries": "اسناد تسویه شده:",
  "rozrep.remaining_entries": "اسناد باقیمانده:",
  "rozrep.system_status": "وضعیت سیستم:",
  "rozrep.online_synced": "آنلاین و هماهنگ",
  "rozrep.from_date": "از تاریخ",
  "rozrep.to_date": "تا تاریخ",
  "rozrep.all_types": "همه انواع",
  "rozrep.debit_credit": "بدهکار / بستانکار",
  "rozrep.all": "همه",
  "rozrep.draft": "پیش‌نویس",
  "rozrep.posted": "ثبت قطعی",
  "rozrep.transferred": "منتقل شده",
  "rozrep.cancelled": "لغو شده",
  "rozrep.reference_no": "شماره مرجع",
  "rozrep.filter_entries_ph": "جستجوی اسناد...",
  "rozrep.reference_ph": "شماره مرجع را وارد کنید",
  "rozrep.bill_no": "شماره فاکتور",
  "rozrep.bill_no_ph": "شماره فاکتور را وارد کنید",
  "rozrep.apply_filter": "اعمال فیلتر",
  "rozrep.reset_filter": "تنظیم مجدد",
  "rozrep.reload": "بارگذاری مجدد",
  "rozrep.actions": "عملیات",
  "rozrep.back": "بازگشت",
  "rozrep.hide_filters": "بستن فیلترها",
  "rozrep.search_filters": "جستجو / فیلترها",
  "rozrep.total_entries": "تعداد کل اسناد",
  "rozrep.showing_page": "نمایش صفحه",
  "rozrep.of": "از",
  "rozrep.loading_entries": "در حال بارگذاری اسناد...",
  "rozrep.no_entries_found": "هیچ سندی برای فیلترهای انتخابی یافت نشد.",
  "rozrep.category_directory": "فهرست دسته‌بندی اسناد روزنامچه",
  "rozrep.category_directory_hint": "برای فیلتر آنی روی دسته کلیک کنید",
  "rozrep.active_view": "نمای فعال",
  "rozrep.click_to_view": "برای مشاهده کلیک کنید",
  "rozrep.currency_label": "ارز",
  "roz.entry_type_po_transfer": "انتقال رزرو خرید",
  "roz.entry_type_po_adv": "پیش‌پرداخت خرید",
  "roz.entry_type_po_rem": "پرداخت باقیمانده خرید",
  "roz.entry_type_journal": "سند روزنامچه",
  "roz.entry_type_bank_dep": "واریز به بانک",
  "roz.entry_type_cash_pay": "پرداخت نقدی",
  "roz.entry_type_cash_rec": "دریافت نقدی",
  "roz.entry_type_expense": "ثبت هزینه",
  "roz.entry_type_fx": "سود / زیان نرخ ارز",
  "status.posted": "ثبت قطعی",
  "status.draft": "پیش‌نویس",
  "status.transferred": "منتقل شده",
  "status.cancelled": "لغو شده"
};

const rozrep_ps = {
  "rozrep.sno": "شمېره",
  "rozrep.date": "نېټه",
  "rozrep.entry_serial": "د ثبت مسلسل شمېره",
  "rozrep.country": "هېواد",
  "rozrep.branch": "څانګه",
  "rozrep.user": "کاروونکی",
  "rozrep.entry_type": "د ثبت ډول",
  "rozrep.roznamcha_type": "د روزنامچې ډول",
  "rozrep.account_no": "د حساب شمېره",
  "rozrep.account_name": "د حساب نوم",
  "rozrep.narration": "تفصیل / څرګندونې",
  "rozrep.currency": "اسعار",
  "rozrep.debit": "ډیبیټ (ورکړه)",
  "rozrep.credit": "کریډټ (اخستنه)",
  "rozrep.balance": "پاتې بیلانس",
  "rozrep.bill_ref": "د بل / حوالې شمېره",
  "rozrep.status": "حالت",
  "rozrep.totals": "ټول مجموعه",
  "rozrep.country_label": "هېواد:",
  "rozrep.branch_name_label": "د څانګې نوم:",
  "rozrep.user_id_label": "د کاروونکي پېژند:",
  "rozrep.user_name_label": "د کاروونکي نوم:",
  "rozrep.role_label": "رول / دنده:",
  "rozrep.datetime_label": "نېټه او وخت:",
  "rozrep.status_label": "حالت:",
  "rozrep.active": "فعال",
  "rozrep.branch_user_details": "د څانګې او کاروونکي تفصیلات",
  "rozrep.global_financial_summary": "عمومي مالي خلاصه",
  "rozrep.total_global_entries": "ټولې عمومي ثبت شوې پېښې:",
  "rozrep.total_bill_entries": "د بلونو ټول ثبتونه:",
  "rozrep.cleared_entries": "تصفیه شوې پېښې:",
  "rozrep.remaining_entries": "پاتې پېښې:",
  "rozrep.system_status": "د سیسټم حالت:",
  "rozrep.online_synced": "آنلاین او همغږی شوی",
  "rozrep.from_date": "له نېټې",
  "rozrep.to_date": "تر نېټې",
  "rozrep.all_types": "ټول ډولونه",
  "rozrep.debit_credit": "ډیبیټ / کریډټ",
  "rozrep.all": "ټول",
  "rozrep.draft": "مسوده",
  "rozrep.posted": "ثبت شوی (پوسټ)",
  "rozrep.transferred": "لېږدول شوی",
  "rozrep.cancelled": "لغوه شوی",
  "rozrep.reference_no": "د حوالې شمېره",
  "rozrep.filter_entries_ph": "پېښې وپلټئ...",
  "rozrep.reference_ph": "د حوالې شمېره ولیکئ",
  "rozrep.bill_no": "د بل شمېره",
  "rozrep.bill_no_ph": "د بل شمېره ولیکئ",
  "rozrep.apply_filter": "پلي کول",
  "rozrep.reset_filter": "بیا تنظیم",
  "rozrep.reload": "بیا تازه کول",
  "rozrep.actions": "کړنې",
  "rozrep.back": "شاته",
  "rozrep.hide_filters": "فلټرونه پټول",
  "rozrep.search_filters": "پلټنه / فلټرونه",
  "rozrep.total_entries": "د ثبتونو ټول شمېر",
  "rozrep.showing_page": "د مخ ښودل",
  "rozrep.of": "له",
  "rozrep.loading_entries": "پېښې بارېږي...",
  "rozrep.no_entries_found": "د ټاکل شوو فلټرونو لپاره هېڅ معلومات ونه موندل شول.",
  "rozrep.category_directory": "د روزنامچې کټګورۍ لارښود",
  "rozrep.category_directory_hint": "د سمدستي فلټر لپاره کټګورۍ وټاکئ",
  "rozrep.active_view": "فعال لید",
  "rozrep.click_to_view": "د لیدلو لپاره کلیک وکړئ",
  "rozrep.currency_label": "اسعار",
  "roz.entry_type_po_transfer": "د پیرودلو بکینګ لېږد",
  "roz.entry_type_po_adv": "د پیرودلو مخکینۍ پیسې",
  "roz.entry_type_po_rem": "د پیرودلو پاتې پیسې",
  "roz.entry_type_journal": "روزنامچه انټري",
  "roz.entry_type_bank_dep": "بانکي جمع کول",
  "roz.entry_type_cash_pay": "نغدي تادیه",
  "roz.entry_type_cash_rec": "نغدي ترلاسه کول",
  "roz.entry_type_expense": "د لګښت انټري",
  "roz.entry_type_fx": "د اسعارو تبادلې ګټه / تاوان",
  "status.posted": "ثبت شوی (پوسټ)",
  "status.draft": "مسوده",
  "status.transferred": "لېږدول شوی",
  "status.cancelled": "لغوه شوی"
};

Object.assign(en, rozrep_en);
Object.assign(ur, rozrep_ur);
Object.assign(ar, rozrep_ar);
Object.assign(fa, rozrep_fa);
Object.assign(ps, rozrep_ps);
// --- END ROZNAMCHA 5-LANG INJECTION ---
`;

content = content.replace(/(const dictionaries: Record<SupportedLanguage, Dict> = \{)/, injection + "\n$1");

fs.writeFileSync(filePath, content, "utf8");
console.log("Successfully injected all 5-language rozrep dictionaries before const dictionaries!");
