// This file is generated automatically by Next.js
// Do not edit this file manually

// Type definitions for Next.js routes

/**
 * Internal types used by the Next.js router and Link component.
 * These types are not meant to be used directly.
 * @internal
 */
declare namespace __next_route_internal_types__ {
  type SearchOrHash = `?${string}` | `#${string}`
  type WithProtocol = `${string}:${string}`

  type Suffix = '' | SearchOrHash

  type SafeSlug<S extends string> = S extends `${string}/${string}`
    ? never
    : S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type CatchAllSlug<S extends string> = S extends `${string}${SearchOrHash}`
    ? never
    : S extends ''
    ? never
    : S

  type OptionalCatchAllSlug<S extends string> =
    S extends `${string}${SearchOrHash}` ? never : S

  type StaticRoutes = 
    | `/`
    | `/api/branch-management/city-branches`
    | `/api/branch-management/countries`
    | `/api/branch-management/country-branches`
    | `/api/branch-management/general-report`
    | `/api/branch-management/super-admin-branches`
    | `/api/check-superadmins`
    | `/api/db-alter`
    | `/api/debug`
    | `/api/debug/fix-roznamcha`
    | `/api/debug/ledgers`
    | `/api/debug/migrate-schema`
    | `/api/debug/reload-schema`
    | `/api/debug2`
    | `/api/dev-reset`
    | `/api/dev-schema`
    | `/api/dev-zod`
    | `/api/dev/migrate`
    | `/api/dev/run-sql`
    | `/api/dev/test-expenses`
    | `/api/dump-fn`
    | `/api/erp/accounting/accounts`
    | `/api/erp/accounting/accounts/lookup`
    | `/api/erp/accounting/ledgers`
    | `/api/erp/accounting/ledgers/opening-balances`
    | `/api/erp/accounting/periods`
    | `/api/erp/accounting/reports/accounts/general`
    | `/api/erp/accounting/reports/global-consolidation`
    | `/api/erp/accounting/reports/ledger/balances`
    | `/api/erp/accounting/reports/ledger/general`
    | `/api/erp/accounting/reports/ledger/ledgers`
    | `/api/erp/accounting/reports/ledger/statement`
    | `/api/erp/accounting/reports/trial-balance`
    | `/api/erp/accounting/reversals`
    | `/api/erp/accounts`
    | `/api/erp/admin/branch-setup/reset`
    | `/api/erp/approvals`
    | `/api/erp/auth/login`
    | `/api/erp/auth/logout`
    | `/api/erp/auth/preview`
    | `/api/erp/auth/session`
    | `/api/erp/banks`
    | `/api/erp/companies`
    | `/api/erp/currency/latest-rate`
    | `/api/erp/currency/monitoring`
    | `/api/erp/customers`
    | `/api/erp/data/table`
    | `/api/erp/data/tables`
    | `/api/erp/dev-cleanup`
    | `/api/erp/dev-cleanup/fix-currencies`
    | `/api/erp/dev-delete-purchases`
    | `/api/erp/dev-reload-schema`
    | `/api/erp/expenses`
    | `/api/erp/expenses/transfer`
    | `/api/erp/goods`
    | `/api/erp/goods/variations`
    | `/api/erp/ledgers`
    | `/api/erp/locations/areas`
    | `/api/erp/locations/branches/main`
    | `/api/erp/locations/bulk-import`
    | `/api/erp/locations/cities`
    | `/api/erp/locations/countries`
    | `/api/erp/locations/districts`
    | `/api/erp/locations/states`
    | `/api/erp/locations/verify-test`
    | `/api/erp/master-data/taxes`
    | `/api/erp/messages`
    | `/api/erp/money-exchange`
    | `/api/erp/multilingual/events`
    | `/api/erp/permissions`
    | `/api/erp/ports/loading`
    | `/api/erp/ports/merge-migration`
    | `/api/erp/ports/received`
    | `/api/erp/products`
    | `/api/erp/purchases/booking-journal-report`
    | `/api/erp/purchases/loading-records`
    | `/api/erp/purchases/orders`
    | `/api/erp/reports/general`
    | `/api/erp/reports/general/accounts`
    | `/api/erp/roznamcha`
    | `/api/erp/sales/orders`
    | `/api/erp/settings/contact-type-rules`
    | `/api/erp/shipping/bl-records`
    | `/api/erp/shipping/line-records`
    | `/api/erp/translations`
    | `/api/erp/users`
    | `/api/erp/users/journal-report`
    | `/api/erp/users/next-code`
    | `/api/fetch-journal`
    | `/api/fix-superadmins`
    | `/api/hello-world`
    | `/api/inspect`
    | `/api/inspect-db`
    | `/api/inspect-users`
    | `/api/scratch`
    | `/api/setup-db`
    | `/api/temp-cleanup`
    | `/api/temp-db-test`
    | `/api/temp-diagnose`
    | `/api/temp-migrate`
    | `/api/temp-read`
    | `/api/temp-reset-db`
    | `/api/test`
    | `/api/test-rpc`
    | `/auth/forgot-password`
    | `/auth/login`
    | `/dashboard`
    | `/dashboard/accounts`
    | `/dashboard/accounts/setup`
    | `/dashboard/accounts/setup-report`
    | `/dashboard/accounts/summary`
    | `/dashboard/accounts/view`
    | `/dashboard/agent`
    | `/dashboard/branch-management`
    | `/dashboard/branch-management/general-report`
    | `/dashboard/city`
    | `/dashboard/clearing-agent`
    | `/dashboard/clearing-agent/agent-custom-entry`
    | `/dashboard/clearing-agent/bill-entry`
    | `/dashboard/clearing-agent/payment-bill-entry`
    | `/dashboard/companies`
    | `/dashboard/country`
    | `/dashboard/data`
    | `/dashboard/documents`
    | `/dashboard/documents/bill-of-lading`
    | `/dashboard/inventory/goods-entry-test`
    | `/dashboard/journal/purchase-order-payment/advance`
    | `/dashboard/journal/purchase-order-payment/charges`
    | `/dashboard/journal/purchase-order-payment/history`
    | `/dashboard/journal/purchase-order-payment/remaining`
    | `/dashboard/ledger`
    | `/dashboard/ledger/branch`
    | `/dashboard/ledger/construction`
    | `/dashboard/ledger/country`
    | `/dashboard/ledger/country/detailed`
    | `/dashboard/ledger/detailed`
    | `/dashboard/ledger/general-report`
    | `/dashboard/ledger/new`
    | `/dashboard/ledger/super-admin`
    | `/dashboard/ledger/super-admin/detailed`
    | `/dashboard/new-entry`
    | `/dashboard/new-entry/accounts/general-report`
    | `/dashboard/new-entry/accounts/super-admin`
    | `/dashboard/new-entry/branch-entry/city-branch`
    | `/dashboard/new-entry/branch-entry/country-branch`
    | `/dashboard/new-entry/branches/super-admin`
    | `/dashboard/new-entry/clearing-agent`
    | `/dashboard/new-entry/goods-master`
    | `/dashboard/new-entry/sales-purchase`
    | `/dashboard/new-entry/shipping-line`
    | `/dashboard/new-entry/users/agent`
    | `/dashboard/new-entry/users/branch`
    | `/dashboard/new-entry/users/country`
    | `/dashboard/new-entry/users/journal-report`
    | `/dashboard/new-entry/users/registration`
    | `/dashboard/new-entry/users/staff`
    | `/dashboard/new-entry/users/super-admin`
    | `/dashboard/purchase/bill-of-lading`
    | `/dashboard/purchase/finalized-purchase-orders`
    | `/dashboard/purchase/loading-form`
    | `/dashboard/purchase/local-purchase`
    | `/dashboard/purchase/new-purchase-booking-order`
    | `/dashboard/purchase/purchase-booking-journal-report`
    | `/dashboard/purchase/purchase-confirm`
    | `/dashboard/purchase/purchase-loading-records`
    | `/dashboard/purchase/purchase-order`
    | `/dashboard/purchase/purchase-order-tracking`
    | `/dashboard/purchase/purchase-order/view`
    | `/dashboard/purchases`
    | `/dashboard/reports`
    | `/dashboard/reports/exchange-rate`
    | `/dashboard/reports/ledger/branch`
    | `/dashboard/reports/ledger/country`
    | `/dashboard/reports/ledger/super-admin`
    | `/dashboard/roznamcha/all`
    | `/dashboard/roznamcha/branch`
    | `/dashboard/roznamcha/branch/cash-entry`
    | `/dashboard/roznamcha/cash-entry`
    | `/dashboard/roznamcha/country`
    | `/dashboard/roznamcha/country/cash-entry`
    | `/dashboard/roznamcha/expenses-bill`
    | `/dashboard/roznamcha/money-exchange`
    | `/dashboard/roznamcha/super-admin`
    | `/dashboard/roznamcha/super-admin/cash-entry`
    | `/dashboard/sales`
    | `/dashboard/sales/local-sales`
    | `/dashboard/sales/sales-confirm`
    | `/dashboard/sales/sales-order`
    | `/dashboard/search`
    | `/dashboard/settings`
    | `/dashboard/settings/account-type`
    | `/dashboard/settings/bank`
    | `/dashboard/settings/company`
    | `/dashboard/settings/company-registration-type`
    | `/dashboard/settings/company-setup`
    | `/dashboard/settings/contact-type`
    | `/dashboard/settings/contract-type`
    | `/dashboard/settings/customers`
    | `/dashboard/settings/customers/setup`
    | `/dashboard/settings/customers/view`
    | `/dashboard/settings/dashboard-settings`
    | `/dashboard/settings/document-type`
    | `/dashboard/settings/location`
    | `/dashboard/settings/location-setup`
    | `/dashboard/settings/locations`
    | `/dashboard/settings/management`
    | `/dashboard/settings/management/chs-products`
    | `/dashboard/settings/management/goods`
    | `/dashboard/settings/management/taxes`
    | `/dashboard/settings/ports`
    | `/dashboard/settings/ports/loading`
    | `/dashboard/settings/ports/received`
    | `/dashboard/settings/warehouse`
    | `/dashboard/shipping-line`
    | `/dashboard/shipping-line/agent-entry`
    | `/dashboard/shipping-line/shipment-details`
    | `/dashboard/shipping-line/shipment-report`
    | `/dashboard/super-admin`
    | `/dashboard/tax`
    | `/dashboard/users`
    | `/dashboard/users/new`
    | `/onboarding`
    | `/test-tax`
  type DynamicRoutes<T extends string = string> = 
    | `/api/erp/accounting/accounts/${SafeSlug<T>}`
    | `/api/erp/accounting/ledgers/${SafeSlug<T>}/statement`
    | `/api/erp/accounting/periods/${SafeSlug<T>}`
    | `/api/erp/accounts/${SafeSlug<T>}`
    | `/api/erp/approvals/${SafeSlug<T>}`
    | `/api/erp/banks/${SafeSlug<T>}`
    | `/api/erp/companies/${SafeSlug<T>}`
    | `/api/erp/customers/${SafeSlug<T>}`
    | `/api/erp/goods/${SafeSlug<T>}`
    | `/api/erp/goods/variations/${SafeSlug<T>}`
    | `/api/erp/locations/areas/${SafeSlug<T>}`
    | `/api/erp/locations/cities/${SafeSlug<T>}`
    | `/api/erp/locations/countries/${SafeSlug<T>}`
    | `/api/erp/locations/districts/${SafeSlug<T>}`
    | `/api/erp/locations/states/${SafeSlug<T>}`
    | `/api/erp/master-data/taxes/${SafeSlug<T>}`
    | `/api/erp/ports/loading/${SafeSlug<T>}`
    | `/api/erp/ports/received/${SafeSlug<T>}`
    | `/api/erp/products/${SafeSlug<T>}`
    | `/api/erp/purchases/orders/${SafeSlug<T>}`
    | `/api/erp/purchases/orders/${SafeSlug<T>}/payments`
    | `/api/erp/purchases/orders/${SafeSlug<T>}/transfer`
    | `/api/erp/roznamcha/${SafeSlug<T>}`
    | `/dashboard/messages/${CatchAllSlug<T>}`
    | `/dashboard/purchase/stock/${SafeSlug<T>}`
    | `/dashboard/reports/${CatchAllSlug<T>}`
    | `/dashboard/settings/template-color/${SafeSlug<T>}`
    | `/dashboard/users/edit/${SafeSlug<T>}`

  type RouteImpl<T> = 
    | StaticRoutes
    | SearchOrHash
    | WithProtocol
    | `${StaticRoutes}${SearchOrHash}`
    | (T extends `${DynamicRoutes<infer _>}${Suffix}` ? T : never)
    
}

declare module 'next' {
  export { default } from 'next/types.js'
  export * from 'next/types.js'

  export type Route<T extends string = string> =
    __next_route_internal_types__.RouteImpl<T>
}

declare module 'next/link' {
  export { useLinkStatus } from 'next/dist/client/link.js'

  import type { LinkProps as OriginalLinkProps } from 'next/dist/client/link.js'
  import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
  import type { UrlObject } from 'url'

  type LinkRestProps = Omit<
    Omit<
      DetailedHTMLProps<
        AnchorHTMLAttributes<HTMLAnchorElement>,
        HTMLAnchorElement
      >,
      keyof OriginalLinkProps
    > &
      OriginalLinkProps,
    'href'
  >

  export type LinkProps<RouteInferType> = LinkRestProps & {
    /**
     * The path or URL to navigate to. This is the only required prop. It can also be an object.
     * @see https://nextjs.org/docs/api-reference/next/link
     */
    href: __next_route_internal_types__.RouteImpl<RouteInferType> | UrlObject
  }

  export default function Link<RouteType>(props: LinkProps<RouteType>): JSX.Element
}

declare module 'next/navigation' {
  export * from 'next/dist/client/components/navigation.js'

  import type { NavigateOptions, AppRouterInstance as OriginalAppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime.js'
  import type { RedirectType } from 'next/dist/client/components/redirect-error.js'
  
  interface AppRouterInstance extends OriginalAppRouterInstance {
    /**
     * Navigate to the provided href.
     * Pushes a new history entry.
     */
    push<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Navigate to the provided href.
     * Replaces the current history entry.
     */
    replace<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>, options?: NavigateOptions): void
    /**
     * Prefetch the provided href.
     */
    prefetch<RouteType>(href: __next_route_internal_types__.RouteImpl<RouteType>): void
  }

  export function useRouter(): AppRouterInstance;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler or Server Action, it will serve a 307/303 to the caller.
   * - In a Server Action, type defaults to 'push' and 'replace' elsewhere.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function redirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
  
  /**
   * This function allows you to redirect the user to another URL. It can be used in
   * [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components),
   * [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers), and
   * [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations).
   *
   * - In a Server Component, this will insert a meta tag to redirect the user to the target page.
   * - In a Route Handler or Server Action, it will serve a 308/303 to the caller.
   *
   * Read more: [Next.js Docs: redirect](https://nextjs.org/docs/app/api-reference/functions/redirect)
   */
  export function permanentRedirect<RouteType>(
    /** The URL to redirect to */
    url: __next_route_internal_types__.RouteImpl<RouteType>,
    type?: RedirectType
  ): never;
}

declare module 'next/form' {
  import type { FormProps as OriginalFormProps } from 'next/dist/client/form.js'

  type FormRestProps = Omit<OriginalFormProps, 'action'>

  export type FormProps<RouteInferType> = {
    /**
     * `action` can be either a `string` or a function.
     * - If `action` is a string, it will be interpreted as a path or URL to navigate to when the form is submitted.
     *   The path will be prefetched when the form becomes visible.
     * - If `action` is a function, it will be called when the form is submitted. See the [React docs](https://react.dev/reference/react-dom/components/form#props) for more.
     */
    action: __next_route_internal_types__.RouteImpl<RouteInferType> | ((formData: FormData) => void)
  } & FormRestProps

  export default function Form<RouteType>(props: FormProps<RouteType>): JSX.Element
}
