// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/setup-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/setup-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/setup-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/setup">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/summary">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/view">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agent">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/branch-management/general-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/branch-management/general-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/branch-management/general-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/branch-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/branch-management">> = Specific
  const handler = {} as typeof import("../../app/dashboard/branch-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/city/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/city">> = Specific
  const handler = {} as typeof import("../../app/dashboard/city/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/clearing-agent/agent-custom-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clearing-agent/agent-custom-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/clearing-agent/agent-custom-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/clearing-agent/bill-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clearing-agent/bill-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/clearing-agent/bill-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/clearing-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clearing-agent">> = Specific
  const handler = {} as typeof import("../../app/dashboard/clearing-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/clearing-agent/payment-bill-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clearing-agent/payment-bill-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/clearing-agent/payment-bill-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/companies">> = Specific
  const handler = {} as typeof import("../../app/dashboard/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/country">> = Specific
  const handler = {} as typeof import("../../app/dashboard/country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/data">> = Specific
  const handler = {} as typeof import("../../app/dashboard/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/documents/bill-of-lading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/documents/bill-of-lading">> = Specific
  const handler = {} as typeof import("../../app/dashboard/documents/bill-of-lading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/documents">> = Specific
  const handler = {} as typeof import("../../app/dashboard/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/inventory/goods-entry-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inventory/goods-entry-test">> = Specific
  const handler = {} as typeof import("../../app/dashboard/inventory/goods-entry-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/journal/purchase-order-payment/advance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/journal/purchase-order-payment/advance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/journal/purchase-order-payment/advance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/journal/purchase-order-payment/charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/journal/purchase-order-payment/charges">> = Specific
  const handler = {} as typeof import("../../app/dashboard/journal/purchase-order-payment/charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/journal/purchase-order-payment/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/journal/purchase-order-payment/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/journal/purchase-order-payment/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/journal/purchase-order-payment/remaining/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/journal/purchase-order-payment/remaining">> = Specific
  const handler = {} as typeof import("../../app/dashboard/journal/purchase-order-payment/remaining/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/branch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/branch">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/branch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/construction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/construction">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/construction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/country/detailed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/country/detailed">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/country/detailed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/country">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/detailed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/detailed">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/detailed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/general-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/general-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/general-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/super-admin/detailed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/super-admin/detailed">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/super-admin/detailed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ledger/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ledger/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ledger/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/messages/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages/[...slug]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/messages/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/accounts/general-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/accounts/general-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/accounts/general-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/accounts/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/accounts/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/accounts/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/branch-entry/city-branch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/branch-entry/city-branch">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/branch-entry/city-branch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/branch-entry/country-branch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/branch-entry/country-branch">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/branch-entry/country-branch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/branches/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/branches/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/branches/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/clearing-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/clearing-agent">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/clearing-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/goods-master/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/goods-master">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/goods-master/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/sales-purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/sales-purchase">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/sales-purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/shipping-line/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/shipping-line">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/shipping-line/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/agent">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/branch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/branch">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/branch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/country">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/journal-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/journal-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/journal-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/registration">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/staff">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-entry/users/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-entry/users/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-entry/users/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/bill-of-lading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/bill-of-lading">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/bill-of-lading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/finalized-purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/finalized-purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/finalized-purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/loading-form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/loading-form">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/loading-form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/local-purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/local-purchase">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/local-purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/new-purchase-booking-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/new-purchase-booking-order">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/new-purchase-booking-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/purchase-booking-journal-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/purchase-booking-journal-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/purchase-booking-journal-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/purchase-confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/purchase-confirm">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/purchase-confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/purchase-loading-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/purchase-loading-records">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/purchase-loading-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/purchase-order-tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/purchase-order-tracking">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/purchase-order-tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/purchase-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/purchase-order">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/purchase-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/purchase-order/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/purchase-order/view">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/purchase-order/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchase/stock/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchase/stock/[type]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchase/stock/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchases">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/[...slug]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/exchange-rate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/exchange-rate">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/exchange-rate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/ledger/branch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/ledger/branch">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/ledger/branch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/ledger/country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/ledger/country">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/ledger/country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/ledger/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/ledger/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/ledger/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/all">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/branch/cash-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/branch/cash-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/branch/cash-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/branch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/branch">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/branch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/cash-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/cash-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/cash-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/country/cash-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/country/cash-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/country/cash-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/country">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/expenses-bill/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/expenses-bill">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/expenses-bill/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/money-exchange/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/money-exchange">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/money-exchange/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/super-admin/cash-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/super-admin/cash-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/super-admin/cash-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/roznamcha/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roznamcha/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/roznamcha/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/sales/local-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sales/local-sales">> = Specific
  const handler = {} as typeof import("../../app/dashboard/sales/local-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sales">> = Specific
  const handler = {} as typeof import("../../app/dashboard/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/sales/sales-confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sales/sales-confirm">> = Specific
  const handler = {} as typeof import("../../app/dashboard/sales/sales-confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/sales/sales-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sales/sales-order">> = Specific
  const handler = {} as typeof import("../../app/dashboard/sales/sales-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/search">> = Specific
  const handler = {} as typeof import("../../app/dashboard/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/account-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/account-type">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/account-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/bank">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/company-registration-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/company-registration-type">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/company-registration-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/company-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/company-setup">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/company-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/company">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/contact-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/contact-type">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/contact-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/contract-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/contract-type">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/contract-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/customers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/customers/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/customers/setup">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/customers/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/customers/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/customers/view">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/customers/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/dashboard-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/dashboard-settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/dashboard-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/document-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/document-type">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/document-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/location-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/location-setup">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/location-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/location/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/location">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/location/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/locations">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/management/chs-products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/management/chs-products">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/management/chs-products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/management/goods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/management/goods">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/management/goods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/management">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/management/taxes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/management/taxes">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/management/taxes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/ports/loading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/ports/loading">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/ports/loading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/ports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/ports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/ports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/ports/received/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/ports/received">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/ports/received/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/template-color/[color]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/template-color/[color]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/template-color/[color]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/warehouse">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shipping-line/agent-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shipping-line/agent-entry">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shipping-line/agent-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shipping-line/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shipping-line">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shipping-line/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shipping-line/shipment-details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shipping-line/shipment-details">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shipping-line/shipment-details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shipping-line/shipment-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shipping-line/shipment-report">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shipping-line/shipment-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/super-admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tax">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-tax">> = Specific
  const handler = {} as typeof import("../../app/test-tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/branch-management/city-branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branch-management/city-branches">> = Specific
  const handler = {} as typeof import("../../app/api/branch-management/city-branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/branch-management/countries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branch-management/countries">> = Specific
  const handler = {} as typeof import("../../app/api/branch-management/countries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/branch-management/country-branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branch-management/country-branches">> = Specific
  const handler = {} as typeof import("../../app/api/branch-management/country-branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/branch-management/general-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branch-management/general-report">> = Specific
  const handler = {} as typeof import("../../app/api/branch-management/general-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/branch-management/super-admin-branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branch-management/super-admin-branches">> = Specific
  const handler = {} as typeof import("../../app/api/branch-management/super-admin-branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/check-superadmins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-superadmins">> = Specific
  const handler = {} as typeof import("../../app/api/check-superadmins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/db-alter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/db-alter">> = Specific
  const handler = {} as typeof import("../../app/api/db-alter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/fix-roznamcha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/fix-roznamcha">> = Specific
  const handler = {} as typeof import("../../app/api/debug/fix-roznamcha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/ledgers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/ledgers">> = Specific
  const handler = {} as typeof import("../../app/api/debug/ledgers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/migrate-schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/migrate-schema">> = Specific
  const handler = {} as typeof import("../../app/api/debug/migrate-schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/reload-schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/reload-schema">> = Specific
  const handler = {} as typeof import("../../app/api/debug/reload-schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug2">> = Specific
  const handler = {} as typeof import("../../app/api/debug2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-reset">> = Specific
  const handler = {} as typeof import("../../app/api/dev-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev-schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-schema">> = Specific
  const handler = {} as typeof import("../../app/api/dev-schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev-zod/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-zod">> = Specific
  const handler = {} as typeof import("../../app/api/dev-zod/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/migrate">> = Specific
  const handler = {} as typeof import("../../app/api/dev/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev/run-sql/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/run-sql">> = Specific
  const handler = {} as typeof import("../../app/api/dev/run-sql/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev/test-expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/test-expenses">> = Specific
  const handler = {} as typeof import("../../app/api/dev/test-expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dump-fn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dump-fn">> = Specific
  const handler = {} as typeof import("../../app/api/dump-fn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/accounts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/accounts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/accounts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/accounts/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/accounts/lookup">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/accounts/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/accounts">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/ledgers/[id]/statement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/ledgers/[id]/statement">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/ledgers/[id]/statement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/ledgers/opening-balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/ledgers/opening-balances">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/ledgers/opening-balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/ledgers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/ledgers">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/ledgers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/periods/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/periods/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/periods/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/periods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/periods">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/periods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/accounts/general/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/accounts/general">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/accounts/general/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/global-consolidation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/global-consolidation">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/global-consolidation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/ledger/balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/ledger/balances">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/ledger/balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/ledger/general/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/ledger/general">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/ledger/general/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/ledger/ledgers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/ledger/ledgers">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/ledger/ledgers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/ledger/statement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/ledger/statement">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/ledger/statement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reports/trial-balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reports/trial-balance">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reports/trial-balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounting/reversals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounting/reversals">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounting/reversals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/accounts">> = Specific
  const handler = {} as typeof import("../../app/api/erp/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/admin/branch-setup/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/admin/branch-setup/reset">> = Specific
  const handler = {} as typeof import("../../app/api/erp/admin/branch-setup/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/approvals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/approvals/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/approvals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/approvals">> = Specific
  const handler = {} as typeof import("../../app/api/erp/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/erp/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/erp/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/auth/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/auth/preview">> = Specific
  const handler = {} as typeof import("../../app/api/erp/auth/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/auth/session">> = Specific
  const handler = {} as typeof import("../../app/api/erp/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/banks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/banks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/banks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/banks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/banks">> = Specific
  const handler = {} as typeof import("../../app/api/erp/banks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/companies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/companies/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/companies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/companies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/companies">> = Specific
  const handler = {} as typeof import("../../app/api/erp/companies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/currency/latest-rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/currency/latest-rate">> = Specific
  const handler = {} as typeof import("../../app/api/erp/currency/latest-rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/currency/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/currency/monitoring">> = Specific
  const handler = {} as typeof import("../../app/api/erp/currency/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/customers">> = Specific
  const handler = {} as typeof import("../../app/api/erp/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/data/table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/data/table">> = Specific
  const handler = {} as typeof import("../../app/api/erp/data/table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/data/tables/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/data/tables">> = Specific
  const handler = {} as typeof import("../../app/api/erp/data/tables/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/dev-cleanup/fix-currencies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/dev-cleanup/fix-currencies">> = Specific
  const handler = {} as typeof import("../../app/api/erp/dev-cleanup/fix-currencies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/dev-cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/dev-cleanup">> = Specific
  const handler = {} as typeof import("../../app/api/erp/dev-cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/dev-delete-purchases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/dev-delete-purchases">> = Specific
  const handler = {} as typeof import("../../app/api/erp/dev-delete-purchases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/dev-reload-schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/dev-reload-schema">> = Specific
  const handler = {} as typeof import("../../app/api/erp/dev-reload-schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/expenses">> = Specific
  const handler = {} as typeof import("../../app/api/erp/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/expenses/transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/expenses/transfer">> = Specific
  const handler = {} as typeof import("../../app/api/erp/expenses/transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/goods/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/goods/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/goods/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/goods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/goods">> = Specific
  const handler = {} as typeof import("../../app/api/erp/goods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/goods/variations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/goods/variations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/goods/variations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/goods/variations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/goods/variations">> = Specific
  const handler = {} as typeof import("../../app/api/erp/goods/variations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/ledgers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/ledgers">> = Specific
  const handler = {} as typeof import("../../app/api/erp/ledgers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/areas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/areas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/areas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/areas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/areas">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/areas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/branches/main/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/branches/main">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/branches/main/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/bulk-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/bulk-import">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/bulk-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/cities/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/cities/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/cities/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/cities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/cities">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/cities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/countries/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/countries/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/countries/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/countries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/countries">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/countries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/districts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/districts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/districts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/districts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/districts">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/districts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/states/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/states/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/states/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/states/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/states">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/states/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/locations/verify-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/locations/verify-test">> = Specific
  const handler = {} as typeof import("../../app/api/erp/locations/verify-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/master-data/taxes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/master-data/taxes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/master-data/taxes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/master-data/taxes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/master-data/taxes">> = Specific
  const handler = {} as typeof import("../../app/api/erp/master-data/taxes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/messages">> = Specific
  const handler = {} as typeof import("../../app/api/erp/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/money-exchange/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/money-exchange">> = Specific
  const handler = {} as typeof import("../../app/api/erp/money-exchange/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/multilingual/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/multilingual/events">> = Specific
  const handler = {} as typeof import("../../app/api/erp/multilingual/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/permissions">> = Specific
  const handler = {} as typeof import("../../app/api/erp/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/ports/loading/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/ports/loading/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/ports/loading/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/ports/loading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/ports/loading">> = Specific
  const handler = {} as typeof import("../../app/api/erp/ports/loading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/ports/merge-migration/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/ports/merge-migration">> = Specific
  const handler = {} as typeof import("../../app/api/erp/ports/merge-migration/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/ports/received/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/ports/received/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/ports/received/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/ports/received/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/ports/received">> = Specific
  const handler = {} as typeof import("../../app/api/erp/ports/received/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/products">> = Specific
  const handler = {} as typeof import("../../app/api/erp/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/purchases/booking-journal-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/purchases/booking-journal-report">> = Specific
  const handler = {} as typeof import("../../app/api/erp/purchases/booking-journal-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/purchases/loading-records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/purchases/loading-records">> = Specific
  const handler = {} as typeof import("../../app/api/erp/purchases/loading-records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/purchases/orders/[id]/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/purchases/orders/[id]/payments">> = Specific
  const handler = {} as typeof import("../../app/api/erp/purchases/orders/[id]/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/purchases/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/purchases/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/purchases/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/purchases/orders/[id]/transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/purchases/orders/[id]/transfer">> = Specific
  const handler = {} as typeof import("../../app/api/erp/purchases/orders/[id]/transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/purchases/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/purchases/orders">> = Specific
  const handler = {} as typeof import("../../app/api/erp/purchases/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/reports/general/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/reports/general/accounts">> = Specific
  const handler = {} as typeof import("../../app/api/erp/reports/general/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/reports/general/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/reports/general">> = Specific
  const handler = {} as typeof import("../../app/api/erp/reports/general/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/roznamcha/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/roznamcha/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/erp/roznamcha/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/roznamcha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/roznamcha">> = Specific
  const handler = {} as typeof import("../../app/api/erp/roznamcha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/sales/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/sales/orders">> = Specific
  const handler = {} as typeof import("../../app/api/erp/sales/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/settings/contact-type-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/settings/contact-type-rules">> = Specific
  const handler = {} as typeof import("../../app/api/erp/settings/contact-type-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/shipping/bl-records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/shipping/bl-records">> = Specific
  const handler = {} as typeof import("../../app/api/erp/shipping/bl-records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/shipping/line-records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/shipping/line-records">> = Specific
  const handler = {} as typeof import("../../app/api/erp/shipping/line-records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/translations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/translations">> = Specific
  const handler = {} as typeof import("../../app/api/erp/translations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/users/journal-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/users/journal-report">> = Specific
  const handler = {} as typeof import("../../app/api/erp/users/journal-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/users/next-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/users/next-code">> = Specific
  const handler = {} as typeof import("../../app/api/erp/users/next-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/erp/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/erp/users">> = Specific
  const handler = {} as typeof import("../../app/api/erp/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fetch-journal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fetch-journal">> = Specific
  const handler = {} as typeof import("../../app/api/fetch-journal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fix-superadmins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fix-superadmins">> = Specific
  const handler = {} as typeof import("../../app/api/fix-superadmins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hello-world/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hello-world">> = Specific
  const handler = {} as typeof import("../../app/api/hello-world/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inspect-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspect-db">> = Specific
  const handler = {} as typeof import("../../app/api/inspect-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inspect-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspect-users">> = Specific
  const handler = {} as typeof import("../../app/api/inspect-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inspect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspect">> = Specific
  const handler = {} as typeof import("../../app/api/inspect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scratch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scratch">> = Specific
  const handler = {} as typeof import("../../app/api/scratch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/setup-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup-db">> = Specific
  const handler = {} as typeof import("../../app/api/setup-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/temp-cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temp-cleanup">> = Specific
  const handler = {} as typeof import("../../app/api/temp-cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/temp-db-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temp-db-test">> = Specific
  const handler = {} as typeof import("../../app/api/temp-db-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/temp-diagnose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temp-diagnose">> = Specific
  const handler = {} as typeof import("../../app/api/temp-diagnose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/temp-migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temp-migrate">> = Specific
  const handler = {} as typeof import("../../app/api/temp-migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/temp-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temp-read">> = Specific
  const handler = {} as typeof import("../../app/api/temp-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/temp-reset-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/temp-reset-db">> = Specific
  const handler = {} as typeof import("../../app/api/temp-reset-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-rpc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-rpc">> = Specific
  const handler = {} as typeof import("../../app/api/test-rpc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test">> = Specific
  const handler = {} as typeof import("../../app/api/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
